---
title: "Two-Profile Common and Unique Latent Transition Analysis"
author: Ivan Jacob Agaloos Pesigan
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Two-Profile Common and Unique Latent Transition Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---






``` r
library(manCULTA)
```



This vignette describes the data generation process for a two-profile CULTA model with a covariate. The CULTA model incorporates covariates, latent categorical variables, trait components, state components, and profile-specific means to simulate longitudinal data with latent profile transitions. Data generation is demonstrated at the end of the vignette using the `GenCULTA2Profiles` function, which integrates all components into a single function call.

Let $i \in \left\{ 1, \ldots, n \right\}$ denote the index for individuals, let $t \in \left\{ 0, \ldots, m - 1 \right\}$ denote the index measurement occasions, let $k \in \left\{ 1, \ldots, p \right\}$ denote the index items, and let $c \in \left\{ 0, 1 \right\}$ be the index of the two latent profiles (profile 0 and profile 1). Let $q$ be the trait dimension, $q = 1$ in this context.


``` r
# dimensions
n # number of individuals
#> [1] 1000
m # measurement occasions
#> [1] 6
p # number of items
#> [1] 4
q # common trait dimension
#> [1] 1
```

## Covariate

The covariate is generated from a normal distribution with mean $\mu_X$ and $\sigma_X$ variance.


``` r
# covariate parameters
mu_x 
#> [1] 11.4009
sigma_x
#> [1] 24.67566
```



## Latent Categorical Variables

Latent categorical variables represent profile membership for each individual at each measurement occasion. In a two-profile model, profile membership is influenced by covariates and previous profile status, following a logistic formulation. We distinguish between:

- Initial profile membership (baseline time point)
- Profile transitions across subsequent time points

We describe both components below.

### Initial Profile Membership

For the first measurement occasion ($t = 0$), profile membership is determined by the following log-odds for belonging to profile 0 (with profile 1 as the reference category):
\begin{equation}
    \left(
        \begin{array}{cc}
            \nu_{0} + \kappa_{0} \times \mathrm{Covariate} & 0 \\
        \end{array}
    \right) .
\end{equation}
The corresponding probability of belonging to each profile is given by:
\begin{equation}
     \left(
       \begin{array}{cc}
           \frac{
             \exp
             \left(
               \nu_{0} + \kappa_{0} \times \mathrm{Covariate}
             \right)
           }{
             \exp
             \left(
               \nu_{0} + \kappa_{0} \times \mathrm{Covariate}
             \right) + 1
           }
           &
           \frac{1}{
             \exp
             \left(
               \nu_{0} + \kappa_{0} \times \mathrm{Covariate}
             \right) + 1
           } \\
       \end{array}
     \right) .
\end{equation}
Profile membership at the first occasion is sampled based on these probabilities.

### Profile Transitions

For subsequent occasions ($t = 1, \ldots, m - 1$), profile transitions depend on the profile at the previous occasion and the covariate. The log-odds for transitioning to profile 0 at time $t$ are given by:
\begin{equation}
    \left(
        \begin{array}{cc}
            \alpha_{0} + \beta_{00} + \gamma_{00} \times \mathrm{Covariate} & 0 \\
	      \alpha_{0} + \gamma_{01} \times \mathrm{Covariate} & 0 \\
        \end{array}
    \right) .
\end{equation}
The probability of transitioning to each profile is computed as:
\begin{equation}
  \left(
    \begin{array}{cc}
      \frac{
        \exp
        \left(
          \alpha_{0} + \beta_{00} + \gamma_{00}
          \times \mathrm{Covariate}
        \right)
      }{
        \exp
        \left(
          \alpha_{0} + \beta_{00} + \gamma_{00}
          \times \mathrm{Covariate}
        \right) + 1
      }
      &
      \frac{1}{
        \exp
        \left(
          \alpha_{0} + \beta_{00} + \gamma_{00}
          \times \mathrm{Covariate}
        \right) + 1
      } \\
      \frac{
        \exp
        \left(
          \alpha_{0} + \gamma_{01} \times \mathrm{Covariate}
        \right)
      }{
        \exp
        \left(
          \alpha_{0} + \gamma_{01} \times \mathrm{Covariate}
        \right) + 1
      }
      &
      \frac{1}{
        \exp
        \left(
          \alpha_{0} + \gamma_{01} \times \mathrm{Covariate}
        \right) + 1
      } \\
    \end{array}
  \right) .
\end{equation}
Profile membership for each subsequent time point is sampled using these transition probabilities, based on the individual's covariate value and previous profile.


``` r
# profile membership and transition parameters
nu_0
#> [1] -3.563
kappa_0
#> [1] 0.122
alpha_0
#> [1] -3.586
beta_00
#> [1] 2.25
gamma_00
#> [1] 0.063
gamma_10
#> [1] 0.094
```



## Trait Components

The trait variate captures between-person differences and is composed of a shared (common) component and item-specific (unique) components. The full decomposition is given by:
\begin{equation}
    \mathrm{Trait}_{i}
    =
    \mathrm{Common\ Trait\ Loading}
    \times \mathrm{Common\ Trait}_{i}
    +
    \mathrm{Unique\ Trait}_{i} .
\end{equation}
We describe each component below.

### Common Trait

The common trait $\mathrm{Common\ Trait}_{i}$ represents shared individual differences that influence all items uniformly. It is drawn from a normal distribution with mean $\mu_t$ and variance $\psi_t$:
\begin{equation}
    \mathrm{Common\ Trait}_{i} \sim \mathcal{N} \left( \mu_t, \psi_t \right)
\end{equation}

The influence of the common trait on each item is determined by the $p \times q$ common trait loading,

### Unique Traits

The unique trait component $\mathrm{Unique\ Trait}_{k, i}$ captures item-specific stable differences and is drawn from a multivariate normal distribution:
\begin{equation}
    \mathrm{Unique\ Trait}_{i} \sim \mathcal{N} \left( \boldsymbol{\mu}_p, \boldsymbol{\Psi}_{p \times p} \right)
\end{equation}

### Combined Trait Variate

The trait variate for item $k$ and individual $i$ is obtained by combining the common and unique trait components:
\begin{equation}
    \mathrm{Trait}_{k, i} = \mathrm{Common\ Trait\ Loading}_{k} \times \mathrm{Common\ Trait}_{i} + \mathrm{Unique\ Trait}_{k, i} .
\end{equation}
The common trait component introduces shared variance across items, while the unique trait component allows for item-specific differences not explained by the common trait.


``` r
# trait parameters
psi_t
#>      [,1]
#> [1,]  0.1
mu_t
#> [1] 0
psi_p
#>      [,1] [,2] [,3] [,4]
#> [1,]  0.1  0.0  0.0  0.0
#> [2,]  0.0  0.1  0.0  0.0
#> [3,]  0.0  0.0  0.5  0.0
#> [4,]  0.0  0.0  0.0  0.5
mu_p
#> [1] 0 0 0 0
common_trait_loading
#>      [,1]
#> [1,]    1
#> [2,]    1
#> [3,]    1
#> [4,]    1
```







## State Components

The state variate is composed of two parts: a common state shared across items, and unique states specific to each item. The full decomposition is given by:
\begin{equation}
  \mathrm{State}_{k, i, t} = \mathrm{Common\ State\ Loading}_{k} \times \mathrm{Common\ State}_{i, t} + \mathrm{Unique\ State}_{k, i, t} .
\end{equation}
We describe each component below.

### Common State

The common state $\mathrm{Common\ State}_{i, t}$ evolves over time following a first-order autoregressive process:
\begin{equation}
  \mathrm{Common\ State}_{i, t} = \phi_{c} \times \mathrm{Common\ State}_{i, t - 1} + \zeta_{i, t} .
\end{equation}
The initial common state is drawn from a normal distribution:
\begin{equation}
  \mathrm{Common\ State}_{i, 0} \sim \mathcal{N} \left( 0, \psi_{s_{0}} \right) .
\end{equation}
The innovation term $\zeta_{i, t}$ is normally distributed:
\begin{equation}
  \zeta_{i, t} \sim \mathcal{N} \left( 0, \psi_{s} \right) .
\end{equation}
The autoregressive parameter $\phi_{c}$ depends on latent profile membership $c$:
\begin{equation}
   \phi_{c} = \phi_{0} + \left( \phi_{1} - \phi_{0} \right) c .
\end{equation}
Here, $\phi_{0}$ and $\phi_{1}$ represent the autoregressive coefficients for profiles coded as 0 and 1, respectively.

### Unique State

The unique state $\mathrm{Unique\ State}_{k, i, t}$ captures item-specific deviations and is drawn from a multivariate normal distribution:
\begin{equation}
  \mathrm{Unique\ State}_{i, t} \sim \mathcal{N} \left( 0, \boldsymbol{\theta} \right)
\end{equation}
where $\boldsymbol{\theta}$ is the item-level covariance matrix for the unique state component.

### Combined State Variate

The state variate for item $k$, individual $i$, and time $t$ combines the common and unique state components:
\begin{equation}
  \mathrm{State}_{k, i, t} = \mathrm{Common\ State\ Loading}_{k} \times \mathrm{Common\ State}_{i, t} + \mathrm{Unique\ State}_{k, i, t}
\end{equation}
The common state loading parameter $\mathrm{Common\ State\ Loading}_{k}$ controls the influence of the shared state on each item.


``` r
# state parameters
common_state_loading
#>      [,1]
#> [1,]    1
#> [2,]    1
#> [3,]    1
#> [4,]    1
phi_0
#> [1] 0
phi_1
#> [1] 0.311
psi_s0
#> [1] 1
psi_s
#> [1] 0.25
theta
#>      [,1] [,2] [,3] [,4]
#> [1,] 0.15 0.00 0.00 0.00
#> [2,] 0.00 0.15 0.00 0.00
#> [3,] 0.00 0.00 0.15 0.00
#> [4,] 0.00 0.00 0.00 0.15
```



## Trait-State Plus Profile Specific Means

The observed variable is given by
\begin{equation}
  Y_{k, i, t} = \mu_{k, c} + \mathrm{Trait}_{k, i} + \mathrm{State}_{k, i, t}
\end{equation}
where $\mu_{k, c}$ is the profile specific mean, while $\mathrm{Trait}_{k, i}$ and $\mathrm{State}_{k, i, t}$ correspond to the trait and state components of the model.


``` r
# profile-specific means
mu_profile
#>       [,1]   [,2]
#> [1,] 2.253 -0.278
#> [2,] 1.493 -0.165
#> [3,] 1.574 -0.199
#> [4,] 1.117 -0.148
```



## Data Generation

The `GenCULTA2Profiles` function puts together all the components described above to generate data using a single function call.


``` r
# complete list of R function arguments

# random seed for reproducibility
set.seed(42)

# dimensions
n # number of individuals
#> [1] 1000
m # measurement occasions
#> [1] 6
p # number of items
#> [1] 4
q # common trait dimension
#> [1] 1

# covariate parameters
mu_x 
#> [1] 11.4009
sigma_x
#> [1] 24.67566

# profile membership and transition parameters
nu_0
#> [1] -3.563
kappa_0
#> [1] 0.122
alpha_0
#> [1] -3.586
beta_00
#> [1] 2.25
gamma_00
#> [1] 0.063
gamma_10
#> [1] 0.094

# trait parameters
psi_t
#>      [,1]
#> [1,]  0.1
mu_t
#> [1] 0
psi_p
#>      [,1] [,2] [,3] [,4]
#> [1,]  0.1  0.0  0.0  0.0
#> [2,]  0.0  0.1  0.0  0.0
#> [3,]  0.0  0.0  0.5  0.0
#> [4,]  0.0  0.0  0.0  0.5
mu_p
#> [1] 0 0 0 0
common_trait_loading
#>      [,1]
#> [1,]    1
#> [2,]    1
#> [3,]    1
#> [4,]    1

# state parameters
common_state_loading
#>      [,1]
#> [1,]    1
#> [2,]    1
#> [3,]    1
#> [4,]    1
phi_0
#> [1] 0
phi_1
#> [1] 0.311
psi_s0
#> [1] 1
psi_s
#> [1] 0.25
theta
#>      [,1] [,2] [,3] [,4]
#> [1,] 0.15 0.00 0.00 0.00
#> [2,] 0.00 0.15 0.00 0.00
#> [3,] 0.00 0.00 0.15 0.00
#> [4,] 0.00 0.00 0.00 0.15

# profile-specific means
mu_profile
#>       [,1]   [,2]
#> [1,] 2.253 -0.278
#> [2,] 1.493 -0.165
#> [3,] 1.574 -0.199
#> [4,] 1.117 -0.148
```


``` r
data <- GenCULTA2Profiles(
  n = n,
  m = m,
  mu_x = mu_x,
  sigma_x = sigma_x,
  nu_0 = nu_0,
  kappa_0 = kappa_0,
  alpha_0 = alpha_0,
  beta_00 = beta_00,
  gamma_00 = gamma_00,
  gamma_10 = gamma_10,
  mu_t = mu_t,
  psi_t = psi_t,
  mu_p = mu_p,
  psi_p = psi_p,
  common_trait_loading = common_trait_loading,
  common_state_loading = common_state_loading,
  phi_0 = phi_0,
  phi_1 = phi_1,
  psi_s0 = psi_s0,
  psi_s = psi_s,
  theta = theta, 
  mu_profile = mu_profile
)
```



## Model Fitting

The `FitCULTA2Profiles` function fits the model using `Mplus`.
**Note:** This function requires that **Mplus** is already installed on the system. To speed up model fitting, consider using the `ncores` argument to leverage multiple cores.


``` r
fit <- FitCULTA2Profiles(data = data)
```




``` r
summary(fit)
#> Call:
#> FitCULTA2Profiles(data = data)
#>                est     se        z      p    2.5%   97.5%
#> mu_10       2.2892 0.0345  66.4408 0.0000  2.2217  2.3567
#> mu_20       1.5475 0.0354  43.6871 0.0000  1.4780  1.6169
#> mu_30       1.6470 0.0391  42.1564 0.0000  1.5705  1.7236
#> mu_40       1.1476 0.0375  30.6217 0.0000  1.0741  1.2210
#> lambda_t_2  1.0188 0.1096   9.2959 0.0000  0.8040  1.2336
#> lambda_s_2  1.0125 0.0149  67.8492 0.0000  0.9832  1.0417
#> lambda_t_3  0.9220 0.1603   5.7508 0.0000  0.6078  1.2362
#> lambda_s_3  0.9907 0.0144  68.6033 0.0000  0.9624  1.0190
#> lambda_t_4  1.1529 0.1623   7.1020 0.0000  0.8348  1.4711
#> lambda_s_4  0.9783 0.0152  64.5268 0.0000  0.9486  1.0080
#> theta_11    0.1491 0.0041  36.2299 0.0000  0.1411  0.1572
#> theta_22    0.1439 0.0039  36.4985 0.0000  0.1362  0.1516
#> theta_33    0.1484 0.0041  36.1035 0.0000  0.1403  0.1564
#> theta_44    0.1497 0.0041  36.4700 0.0000  0.1417  0.1577
#> phi_0      -0.0364 0.0465  -0.7824 0.4340 -0.1274  0.0547
#> psi_t       0.0854 0.0158   5.4060 0.0000  0.0544  0.1163
#> psi_p_11    0.0914 0.0098   9.3505 0.0000  0.0723  0.1106
#> psi_p_22    0.0848 0.0096   8.8383 0.0000  0.0660  0.1036
#> psi_p_33    0.5065 0.0259  19.5887 0.0000  0.4558  0.5572
#> psi_p_44    0.5112 0.0261  19.5831 0.0000  0.4600  0.5623
#> psi_s0      1.0311 0.0589  17.5197 0.0000  0.9157  1.1464
#> psi_s       0.2463 0.0092  26.7726 0.0000  0.2283  0.2643
#> mu_11      -0.2877 0.0181 -15.8557 0.0000 -0.3232 -0.2521
#> mu_21      -0.1843 0.0175 -10.5194 0.0000 -0.2186 -0.1499
#> mu_31      -0.1778 0.0268  -6.6429 0.0000 -0.2303 -0.1254
#> mu_41      -0.1727 0.0277  -6.2303 0.0000 -0.2270 -0.1184
#> phi_1       0.3142 0.0179  17.5229 0.0000  0.2790  0.3493
#> nu_0       -4.2692 0.4096 -10.4237 0.0000 -5.0719 -3.4664
#> alpha_0    -3.5916 0.1635 -21.9696 0.0000 -3.9120 -3.2712
#> kappa_0     0.1578 0.0273   5.7834 0.0000  0.1043  0.2112
#> beta_00     2.0830 0.3584   5.8113 0.0000  1.3805  2.7856
#> gamma_00    0.0780 0.0208   3.7502 0.0002  0.0372  0.1187
#> gamma_10    0.0990 0.0122   8.1211 0.0000  0.0751  0.1229
```

## Parameter Recovery

Parameter recovery was assessed by calculating the differences between the population values and the estimated parameters.



Table: Parameter Recovery

|           | Parameter|   Estimate| Difference|
|:----------|---------:|----------:|----------:|
|mu_10      |     2.253|  2.2892154| -0.0362154|
|mu_20      |     1.493|  1.5474649| -0.0544649|
|mu_30      |     1.574|  1.6470261| -0.0730261|
|mu_40      |     1.117|  1.1475578| -0.0305578|
|lambda_t_2 |     1.000|  1.0188157| -0.0188157|
|lambda_s_2 |     1.000|  1.0124533| -0.0124533|
|lambda_t_3 |     1.000|  0.9219963|  0.0780037|
|lambda_s_3 |     1.000|  0.9906921|  0.0093079|
|lambda_t_4 |     1.000|  1.1529289| -0.1529289|
|lambda_s_4 |     1.000|  0.9782699|  0.0217301|
|theta_11   |     0.150|  0.1491231|  0.0008769|
|theta_22   |     0.150|  0.1439066|  0.0060934|
|theta_33   |     0.150|  0.1483516|  0.0016484|
|theta_44   |     0.150|  0.1496998|  0.0003002|
|phi_0      |     0.000| -0.0363620|  0.0363620|
|psi_t      |     0.100|  0.0853758|  0.0146242|
|psi_p_11   |     0.100|  0.0914291|  0.0085709|
|psi_p_22   |     0.100|  0.0848098|  0.0151902|
|psi_p_33   |     0.500|  0.5064767| -0.0064767|
|psi_p_44   |     0.500|  0.5111656| -0.0111656|
|psi_s0     |     1.000|  1.0310506| -0.0310506|
|psi_s      |     0.250|  0.2462948|  0.0037052|
|mu_11      |    -0.278| -0.2876850|  0.0096850|
|mu_21      |    -0.165| -0.1842756|  0.0192756|
|mu_31      |    -0.199| -0.1778213| -0.0211787|
|mu_41      |    -0.148| -0.1727158|  0.0247158|
|phi_1      |     0.311|  0.3141922| -0.0031922|
|nu_0       |    -3.563| -4.2691825|  0.7061825|
|alpha_0    |    -3.586| -3.5915924|  0.0055924|
|kappa_0    |     0.122|  0.1577775| -0.0357775|
|beta_00    |     2.250|  2.0830270|  0.1669730|
|gamma_00   |     0.063|  0.0779785| -0.0149785|
|gamma_10   |     0.094|  0.0989865| -0.0049865|



## Methods

The `FitCULTA2Profiles` function has a number of methods including the following:

- `print`
- `summary`
- `converged`
- `confint`
- `coef`
- `vcov`
- `logLik`
- `AIC`
- `BIC`
- `entropy`
- `anova`






















### Mplus Script Used


```
TITLE:
  2-Profile CULTA with Covariate;

DATA:
  FILE = data.dat;

VARIABLE:
  NAMES =
    id
    x
    y1t0
    y2t0
    y3t0
    y4t0
    y1t1
    y2t1
    y3t1
    y4t1
    y1t2
    y2t2
    y3t2
    y4t2
    y1t3
    y2t3
    y3t3
    y4t3
    y1t4
    y2t4
    y3t4
    y4t4
    y1t5
    y2t5
    y3t5
    y4t5
  ;
  USEVARIABLES =
    x
    y1t0
    y2t0
    y3t0
    y4t0
    y1t1
    y2t1
    y3t1
    y4t1
    y1t2
    y2t2
    y3t2
    y4t2
    y1t3
    y2t3
    y3t3
    y4t3
    y1t4
    y2t4
    y3t4
    y4t4
    y1t5
    y2t5
    y3t5
    y4t5
  ;
  IDVARIABLE = id;
  CLASSES =
    c0(2)
    c1(2)
    c2(2)
    c3(2)
    c4(2)
    c5(2)
  ;

ANALYSIS:
  TYPE = MIXTURE;
  STARTS = 20 4;
  STSCALE = 5;
  STITERATIONS = 10;
  PROCESS = 1;
  MODEL = NOCOV;

MODEL:
  %OVERALL%
    ! common trait ------------------------------------------------------

    !! factor loadings
    !!! t = 0
    t BY y1t0@1;
    t BY y2t0 (lambdat2);
    t BY y3t0 (lambdat3);
    t BY y4t0 (lambdat4);
    !!! t = 1
    t BY y1t1@1;
    t BY y2t1 (lambdat2);
    t BY y3t1 (lambdat3);
    t BY y4t1 (lambdat4);
    !!! t = 2
    t BY y1t2@1;
    t BY y2t2 (lambdat2);
    t BY y3t2 (lambdat3);
    t BY y4t2 (lambdat4);
    !!! t = 3
    t BY y1t3@1;
    t BY y2t3 (lambdat2);
    t BY y3t3 (lambdat3);
    t BY y4t3 (lambdat4);
    !!! t = 4
    t BY y1t4@1;
    t BY y2t4 (lambdat2);
    t BY y3t4 (lambdat3);
    t BY y4t4 (lambdat4);
    !!! t = 5
    t BY y1t5@1;
    t BY y2t5 (lambdat2);
    t BY y3t5 (lambdat3);
    t BY y4t5 (lambdat4);

    !! latent mean
    [ t@0 ];

    !! latent variance
    t (psit);

    ! unique traits -----------------------------------------------------

    !! factor loadings
    !!! k = 1
    u1 BY y1t0@1;
    u1 BY y1t1@1;
    u1 BY y1t2@1;
    u1 BY y1t3@1;
    u1 BY y1t4@1;
    u1 BY y1t5@1;
    !!! k = 2
    u2 BY y2t0@1;
    u2 BY y2t1@1;
    u2 BY y2t2@1;
    u2 BY y2t3@1;
    u2 BY y2t4@1;
    u2 BY y2t5@1;
    !!! k = 3
    u3 BY y3t0@1;
    u3 BY y3t1@1;
    u3 BY y3t2@1;
    u3 BY y3t3@1;
    u3 BY y3t4@1;
    u3 BY y3t5@1;
    !!! k = 4
    u4 BY y4t0@1;
    u4 BY y4t1@1;
    u4 BY y4t2@1;
    u4 BY y4t3@1;
    u4 BY y4t4@1;
    u4 BY y4t5@1;

    !! latent means
    [ u1@0 ];
    [ u2@0 ];
    [ u3@0 ];
    [ u4@0 ];

    !! latent variances
    u1 (psip1);
    u2 (psip2);
    u3 (psip3);
    u4 (psip4);

    ! common states -----------------------------------------------------

    !! factor loadings
    !!! t = 0
    s0 BY y1t0@1;
    s0 BY y2t0 (lambdas2);
    s0 BY y3t0 (lambdas3);
    s0 BY y4t0 (lambdas4);
    !!! t = 1
    s1 BY y1t1@1;
    s1 BY y2t1 (lambdas2);
    s1 BY y3t1 (lambdas3);
    s1 BY y4t1 (lambdas4);
    !!! t = 2
    s2 BY y1t2@1;
    s2 BY y2t2 (lambdas2);
    s2 BY y3t2 (lambdas3);
    s2 BY y4t2 (lambdas4);
    !!! t = 3
    s3 BY y1t3@1;
    s3 BY y2t3 (lambdas2);
    s3 BY y3t3 (lambdas3);
    s3 BY y4t3 (lambdas4);
    !!! t = 4
    s4 BY y1t4@1;
    s4 BY y2t4 (lambdas2);
    s4 BY y3t4 (lambdas3);
    s4 BY y4t4 (lambdas4);
    !!! t = 5
    s5 BY y1t5@1;
    s5 BY y2t5 (lambdas2);
    s5 BY y3t5 (lambdas3);
    s5 BY y4t5 (lambdas4);

    !! latent means
    [ s0@0 ];
    [ s1@0 ];
    [ s2@0 ];
    [ s3@0 ];
    [ s4@0 ];
    [ s5@0 ];

    !! latent variance of s0
    s0 (psis0);

    !! variance of the process noise
    s1 (psis);
    s2 (psis);
    s3 (psis);
    s4 (psis);
    s5 (psis);

    ! unique states -----------------------------------------------------

    !! variances
    !!! t = 0
    y1t0 (theta11);
    y2t0 (theta22);
    y3t0 (theta33);
    y4t0 (theta44);
    !!! t = 1
    y1t1 (theta11);
    y2t1 (theta22);
    y3t1 (theta33);
    y4t1 (theta44);
    !!! t = 2
    y1t2 (theta11);
    y2t2 (theta22);
    y3t2 (theta33);
    y4t2 (theta44);
    !!! t = 3
    y1t3 (theta11);
    y2t3 (theta22);
    y3t3 (theta33);
    y4t3 (theta44);
    !!! t = 4
    y1t4 (theta11);
    y2t4 (theta22);
    y3t4 (theta33);
    y4t4 (theta44);
    !!! t = 5
    y1t5 (theta11);
    y2t5 (theta22);
    y3t5 (theta33);
    y4t5 (theta44);

    ! constrained intercepts --------------------------------------------

    !! t = 0
    [ y1t0@0 ];
    [ y2t0@0 ];
    [ y3t0@0 ];
    [ y4t0@0 ];
    !! t = 1
    [ y1t1@0 ];
    [ y2t1@0 ];
    [ y3t1@0 ];
    [ y4t1@0 ];
    !! t = 2
    [ y1t2@0 ];
    [ y2t2@0 ];
    [ y3t2@0 ];
    [ y4t2@0 ];
    !! t = 3
    [ y1t3@0 ];
    [ y2t3@0 ];
    [ y3t3@0 ];
    [ y4t3@0 ];
    !! t = 4
    [ y1t4@0 ];
    [ y2t4@0 ];
    [ y3t4@0 ];
    [ y4t4@0 ];
    !! t = 5
    [ y1t5@0 ];
    [ y2t5@0 ];
    [ y3t5@0 ];
    [ y4t5@0 ];

    ! lta ---------------------------------------------------------------

    !! initial profile membership
    [ c0#1 ] (nu0);
    c0#1 ON x (kappa0);

    !! profile transitions
    [ c1#1 ] (alpha0);
    [ c2#1 ] (alpha0);
    [ c3#1 ] (alpha0);
    [ c4#1 ] (alpha0);
    [ c5#1 ] (alpha0);
    c1#1 ON c0#1 (beta00);
    c2#1 ON c1#1 (beta00);
    c3#1 ON c2#1 (beta00);
    c4#1 ON c3#1 (beta00);
    c5#1 ON c4#1 (beta00);

MODEL c0:
  %c0#1%
    ! profile specific means
    [ y1t0 ] (mu10);
    [ y2t0 ] (mu20);
    [ y3t0 ] (mu30);
    [ y4t0 ] (mu40);

    ! covariate
    c1 ON x (gamma00);

  %c0#2%
    ! profile specific means
    [ y1t0 ] (mu11);
    [ y2t0 ] (mu21);
    [ y3t0 ] (mu31);
    [ y4t0 ] (mu41);

    ! covariate
    c1 ON x (gamma10);

MODEL c1:
  %c1#1%
    ! profile specific means
    [ y1t1 ] (mu10);
    [ y2t1 ] (mu20);
    [ y3t1 ] (mu30);
    [ y4t1 ] (mu40);

    ! covariate
    c2 ON x (gamma00);

    ! inertia
    s1 ON s0 (phi0);

  %c1#2%
    ! profile specific means
    [ y1t1 ] (mu11);
    [ y2t1 ] (mu21);
    [ y3t1 ] (mu31);
    [ y4t1 ] (mu41);

    ! covariate
    c2 ON x (gamma10);

    ! inertia
    s1 ON s0 (phi1);

MODEL c2:
  %c2#1%
    ! profile specific means
    [ y1t2 ] (mu10);
    [ y2t2 ] (mu20);
    [ y3t2 ] (mu30);
    [ y4t2 ] (mu40);

    ! covariate
    c3 ON x (gamma00);

    ! inertia
    s2 ON s1 (phi0);

  %c2#2%
    ! profile specific means
    [ y1t2 ] (mu11);
    [ y2t2 ] (mu21);
    [ y3t2 ] (mu31);
    [ y4t2 ] (mu41);

    ! covariate
    c3 ON x (gamma10);

    ! inertia
    s2 ON s1 (phi1);

MODEL c3:
  %c3#1%
    ! profile specific means
    [ y1t3 ] (mu10);
    [ y2t3 ] (mu20);
    [ y3t3 ] (mu30);
    [ y4t3 ] (mu40);

    ! covariate
    c4 ON x (gamma00);

    ! inertia
    s3 ON s2 (phi0);

  %c3#2%
    ! profile specific means
    [ y1t3 ] (mu11);
    [ y2t3 ] (mu21);
    [ y3t3 ] (mu31);
    [ y4t3 ] (mu41);

    ! covariate
    c4 ON x (gamma10);

    ! inertia
    s3 ON s2 (phi1);

MODEL c4:
  %c4#1%
    ! profile specific means
    [ y1t4 ] (mu10);
    [ y2t4 ] (mu20);
    [ y3t4 ] (mu30);
    [ y4t4 ] (mu40);

    ! covariate
    c5 ON x (gamma00);

    ! inertia
    s4 ON s3 (phi0);

  %c4#2%
    ! profile specific means
    [ y1t4 ] (mu11);
    [ y2t4 ] (mu21);
    [ y3t4 ] (mu31);
    [ y4t4 ] (mu41);

    ! covariate
    c5 ON x (gamma10);

    ! inertia
    s4 ON s3 (phi1);

MODEL c5:
  %c5#1%
    ! profile specific means
    [ y1t5 ] (mu10);
    [ y2t5 ] (mu20);
    [ y3t5 ] (mu30);
    [ y4t5 ] (mu40);

    ! inertia
    s5 ON s4 (phi0);

  %c5#2%
    ! profile specific means
    [ y1t5 ] (mu11);
    [ y2t5 ] (mu21);
    [ y3t5 ] (mu31);
    [ y4t5 ] (mu41);

    ! inertia
    s5 ON s4 (phi1);


MODEL CONSTRAINT:
  ! means for the first profile are higher than the second
  mu10 > mu11;
  mu20 > mu21;
  mu30 > mu31;
  mu40 > mu41;

  ! make sure variances are greater than zero
  psit > 0;
  psip1 > 0;
  psip2 > 0;
  psip3 > 0;
  psip4 > 0;
  psis0 > 0;
  psis > 0;
  theta11 > 0;
  theta22 > 0;
  theta33 > 0;
  theta44 > 0;

OUTPUT:
  TECH1
  TECH3
  TECH4
  TECH7
  TECH8
  TECH12
  TECH13
  TECH15
  ENTROPY;

SAVEDATA:
  ESTIMATES = fn_ICSIHjJ462fvaczvQI98_estimates.dat;
  RESULTS = fn_ICSIHjJ462fvaczvQI98_results.dat;
  TECH3 = fn_ICSIHjJ462fvaczvQI98_tech3.dat;
  TECH4 = fn_ICSIHjJ462fvaczvQI98_tech4.dat;
  FILE = fn_ICSIHjJ462fvaczvQI98_cprobs.dat;
  SAVE = CPROBABILITIES;
```
