# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.CommonState2Profiles <- function(categorical, beta_0, beta_1, psi_s0, psi_s) {
    .Call(`_manCULTA_CommonState2Profiles`, categorical, beta_0, beta_1, psi_s0, psi_s)
}

.RandMultiNormMean <- function(n, mu, sigma) {
    .Call(`_manCULTA_RandMultiNormMean`, n, mu, sigma)
}

.RandMultiNorm <- function(n, sigma) {
    .Call(`_manCULTA_RandMultiNorm`, n, sigma)
}

.State <- function(common_state, common_state_loading, theta) {
    .Call(`_manCULTA_State`, common_state, common_state_loading, theta)
}

.TraitMean <- function(common_trait, unique_trait, common_trait_loading, grand_mean) {
    .Call(`_manCULTA_TraitMean`, common_trait, unique_trait, common_trait_loading, grand_mean)
}

.TraitState2Profiles <- function(mu_profile, trait, state, categorical) {
    .Call(`_manCULTA_TraitState2Profiles`, mu_profile, trait, state, categorical)
}

.Trait <- function(common_trait, unique_trait, common_trait_loading) {
    .Call(`_manCULTA_Trait`, common_trait, unique_trait, common_trait_loading)
}

